Repository cta-observatory/magic-cta-pipe, pull requests merged in 2024-02, with the labels that each got.

#197 Add in README a note about different LST-1 data and MCP versions.
  README.rst
  docs/index.rst
Labels: documentation-only

#200 Fix tests docs
  .github/workflows/ci.yml
  docs/conf.py
Labels: documentation-only

#189 Catch the numpy LinAlgError when recostructing the stereo parameters.
  magicctapipe/conftest.py
  magicctapipe/scripts/lst1_magic/lst1_magic_stereo_reco.py
Labels: maintenance

#193 Write MAGIC-only subarray
  magicctapipe/scripts/lst1_magic/magic_calib_to_dl1.py
Labels: maintenance

#192 Simplify reassignment of tel_ids.
  magicctapipe/scripts/lst1_magic/magic_calib_to_dl1.py
Labels: refactoring, maintenance

#205 Sort files and assign train and test files.
  magicctapipe/conftest.py
Labels: maintenance

#204 Cache test data
  .github/workflows/ci.yml
Labels: maintenance

#203 Use same scipy requirements as lstchain.
  environment.yml
  setup.cfg
Labels: maintenance

#202 Add citation file.
  CITATION.bib
Labels: documentation-only

#208 Drop NaN events also in MCs when loading DL2 data.
  magicctapipe/io/io.py
Labels: fix

#206 Remove averaging of positions in MCs.
  magicctapipe/scripts/lst1_magic/lst1_magic_mc_dl0_to_dl1.py
Labels: maintenance

#211 test lstchain 0.9 files
  magicctapipe/conftest.py
  magicctapipe/io/tests/test_io.py
Labels: maintenance, tests
