Repository cta-observatory/magic-cta-pipe, pull requests merged in 2024-01, with the labels that each got.

#148 ctapipe 0.19 & co.
  .github/workflows/ci.yml
  docs/conf.py
  environment.yml
  magicctapipe/conftest.py
  magicctapipe/image/tests/test_calib.py
  magicctapipe/io/containers.py
  magicctapipe/io/gadf.py
  magicctapipe/io/io.py
  magicctapipe/io/tests/test_gadf.py
  magicctapipe/io/tests/test_io.py
  magicctapipe/io/tests/test_io_monly.py
  magicctapipe/resources/test_config.yaml
  magicctapipe/resources/test_config_general.yaml
  magicctapipe/resources/test_config_general_4LST.yaml
  magicctapipe/resources/test_config_monly.yaml
  magicctapipe/scripts/lst1_magic/config.yaml
  magicctapipe/scripts/lst1_magic/create_dl3_index_files.py
  magicctapipe/scripts/lst1_magic/lst1_magic_create_irf.py
  magicctapipe/scripts/lst1_magic/lst1_magic_dl1_stereo_to_dl2.py
  magicctapipe/scripts/lst1_magic/lst1_magic_dl2_to_dl3.py
  magicctapipe/scripts/lst1_magic/lst1_magic_mc_dl0_to_dl1.py
  magicctapipe/scripts/lst1_magic/lst1_magic_mc_muon_analysis.py
  magicctapipe/scripts/lst1_magic/lst1_magic_stereo_reco.py
  magicctapipe/scripts/lst1_magic/magic_calib_to_dl1.py
  magicctapipe/scripts/lst1_magic/muon_analysis_LST_or_MAGIC_data.py
  magicctapipe/utils/__init__.py
  magicctapipe/utils/camera_geometry.py
  pyproject.toml
  setup.cfg
  setup.py
Labels: enhancement, maintenance

#179 added new tests
  .github/workflows/ci.yml
  environment.yml
  magicctapipe/conftest.py
  magicctapipe/io/io.py
  magicctapipe/io/tests/test_io.py
  magicctapipe/io/tests/test_io_monly.py
  magicctapipe/resources/test_check_list.yaml
  magicctapipe/scripts/lst1_magic/lst1_magic_dl1_stereo_to_dl2.py
Labels: maintenance

#186 Release v0.4.0
  .github/workflows/deploy.yml
  Makefile
  README.rst
  docs/_static/switcher.json
Labels: release

#188 Fix description for pypi
  .pre-commit-config.yaml
  MANIFEST.in
  docs/requirements.txt
  setup.cfg
Labels: documentation-only, fix

#149 Update CI
  .github/dependabot.yml
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  .readthedocs.yaml
  README.rst
  pyproject.toml
Labels: maintenance

#173 Update versions of setuptools[_scm].
  .github/workflows/ci.yml
  environment.yml
  setup.cfg
Labels: maintenance

#196 Update to v0.4.1
  README.rst
  docs/_static/switcher.json
Labels: release
